services:
  web:
    build:
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .envs/.fastapi
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
    command: sh -c "uvicorn main:app --host 0.0.0.0 --reload"

  db:
    restart: always
    image: postgres:15.3-alpine
    env_file:
      - .envs/.postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
        test: sh -c "pg_isready -U postgres"
        interval: 3s
        timeout: 3s
        retries: 5

volumes:
  postgres_data:
